[theme]
base = "dark"
primaryColor = "#1f77b4"       # azul escuro
backgroundColor = "#0e1117"    # quase preto
secondaryBackgroundColor = "#1a1d23"
textColor = "#e0e0e0"          # cinza claro
font = "sans serif"
